"""Optional AI-assisted summaries. Advisory only, and nothing is sent.

Four things an assistant could usefully draft:

    seller summary · deal summary · next action · follow-up suggestion

Two rules, enforced here rather than left to discipline:

* **advisory only.** Output is a suggestion for you to read. It never changes
  a status, never writes a note, never alters a score, and never sends
  anything to anyone.
* **no provider is connected.** :class:`RuleBasedNoteWriter` is the default
  and uses no AI at all — it states plainly what the stored record already
  says. An LLM adapter would implement the same interface.

Everything a writer produces is stamped ``ADVISORY`` and carries the source
that produced it, so an AI-drafted line can never be mistaken for a fact the
engine established.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Any, Dict, List, Optional

from ..formatting import money
from .base import Integration, IntegrationNotConfigured

#: Prefix on every generated line. Never removed.
ADVISORY_PREFIX = "ADVISORY"


@dataclass
class Suggestion:
    """One advisory line. Never authoritative, never acted on automatically."""

    kind: str  # seller_summary | deal_summary | next_action | follow_up
    text: str
    reason: str = ""
    source: str = "rule-based"
    property_id: str = ""

    def render(self) -> str:
        head = f"{self.kind.replace('_', ' ').upper()}:\n  {self.text}"
        if self.reason:
            head += f"\n\nREASON:\n  {self.reason}"
        return head + f"\n\n[{ADVISORY_PREFIX} — generated by {self.source}, not a fact " \
                      "the engine established. Read it, then decide.]"

    def as_dict(self) -> Dict[str, Any]:
        return {
            "kind": self.kind,
            "text": self.text,
            "reason": self.reason,
            "source": self.source,
            "property_id": self.property_id,
            "advisory": True,
        }


class NoteWriter(Integration):
    """Generates advisory summaries. Implementations must never act."""

    kind = "ai-notes"

    def seller_summary(self, context: Dict[str, Any]) -> Suggestion:
        raise NotImplementedError

    def deal_summary(self, context: Dict[str, Any]) -> Suggestion:
        raise NotImplementedError

    def next_action(self, context: Dict[str, Any]) -> Suggestion:
        raise NotImplementedError

    def follow_up_suggestion(self, context: Dict[str, Any]) -> Suggestion:
        raise NotImplementedError

    def all_suggestions(self, context: Dict[str, Any]) -> List[Suggestion]:
        return [
            self.seller_summary(context),
            self.deal_summary(context),
            self.next_action(context),
            self.follow_up_suggestion(context),
        ]


class RuleBasedNoteWriter(NoteWriter):
    """The default. No AI, no network, no credentials — just plain restatement.

    Everything it says is already in the record. That is the point: it is
    useful without a provider, and it cannot hallucinate, because it does not
    generate anything it was not given.
    """

    name = "rule-based"
    is_local = True

    def seller_summary(self, context: Dict[str, Any]) -> Suggestion:
        owner = context.get("owner_name") or "The owner"
        attempts = context.get("contact_attempts") or 0
        last = context.get("last_outcome")
        response = context.get("seller_response")

        parts = [f"{owner}."]
        if attempts:
            parts.append(
                f"{attempts} contact attempt(s) logged"
                + (f", most recently {last}." if last else ".")
            )
        else:
            parts.append("No contact attempts logged yet.")
        if response:
            parts.append(f"Last recorded response: {response}.")
        if context.get("is_test_data"):
            parts.append(
                "Contact details on file are FICTIONAL TEST DATA and must not be used."
            )
        return Suggestion(
            "seller_summary", " ".join(parts), property_id=context.get("property_id", "")
        )

    def deal_summary(self, context: Dict[str, Any]) -> Suggestion:
        arv, repairs = context.get("arv"), context.get("repairs")
        mao, fee = context.get("mao"), context.get("potential_fee")
        target = context.get("target_fee", 18_000.0)

        if arv is None or mao is None:
            return Suggestion(
                "deal_summary",
                "The deal math is incomplete — no verified ARV or no rehab figure, "
                "so there is no MAO to talk about.",
                reason="Missing inputs, not a bad deal.",
                property_id=context.get("property_id", ""),
            )
        text = (
            f"ARV {money(arv)} less {money(repairs)} of repairs puts the MAO at "
            f"{money(mao)}. Asking is {money(context.get('asking_price'))}."
        )
        reason = ""
        if fee is not None:
            reason = (
                f"At the price on the table the deal supports {money(fee)} of "
                f"assignment fee against a {money(target)} target"
            )
            reason += (
                ". That is below target — a label, not a rejection; the deal score "
                "decides." if fee < target else "."
            )
        return Suggestion(
            "deal_summary", text, reason, property_id=context.get("property_id", "")
        )

    def next_action(self, context: Dict[str, Any]) -> Suggestion:
        action = context.get("next_action") or "REVIEW"
        reason = context.get("action_reason") or "No specific blocker recorded."
        return Suggestion(
            "next_action", str(action), reason, property_id=context.get("property_id", "")
        )

    def follow_up_suggestion(self, context: Dict[str, Any]) -> Suggestion:
        due = context.get("next_follow_up")
        last = context.get("last_outcome")
        if due:
            return Suggestion(
                "follow_up", f"Already scheduled for {due}.",
                f"Last outcome was {last}." if last else "",
                property_id=context.get("property_id", ""),
            )
        if last in ("CALL_BACK", "NO_ANSWER", "LEFT_VOICEMAIL", "INTERESTED"):
            return Suggestion(
                "follow_up",
                "Schedule a follow-up — nothing is on the calendar.",
                f"The last outcome was {last}, which expects one.",
                property_id=context.get("property_id", ""),
            )
        return Suggestion(
            "follow_up", "No follow-up needed yet.",
            "No outcome on file that expects one.",
            property_id=context.get("property_id", ""),
        )


class LlmNoteWriter(NoteWriter):
    """**NOT CONNECTED.** Interface for an LLM-backed writer.

    An implementation must keep the same contract: advisory output only, no
    status changes, no sends, and every line stamped ADVISORY. Property data
    is the user's business record — decide deliberately what leaves the
    machine before wiring this up, and never include owner contact details in
    a prompt.
    """

    name = "llm"
    required_settings = ("AI_API_KEY", "AI_MODEL")

    def _refuse(self) -> Suggestion:
        raise IntegrationNotConfigured(
            "No AI provider is connected. The rule-based writer works today and "
            "needs no credentials; it restates the record rather than generating "
            "anything new."
        )

    def seller_summary(self, context: Dict[str, Any]) -> Suggestion:
        return self._refuse()

    def deal_summary(self, context: Dict[str, Any]) -> Suggestion:
        return self._refuse()

    def next_action(self, context: Dict[str, Any]) -> Suggestion:
        return self._refuse()

    def follow_up_suggestion(self, context: Dict[str, Any]) -> Suggestion:
        return self._refuse()


NOTE_WRITERS = {
    "none": RuleBasedNoteWriter,
    "rule-based": RuleBasedNoteWriter,
    "llm": LlmNoteWriter,
}


def get_note_writer(name: str = "none") -> NoteWriter:
    key = (name or "none").strip().lower()
    factory = NOTE_WRITERS.get(key)
    if factory is None:
        raise ValueError(
            f"unknown AI adapter '{name}'. Available: {', '.join(NOTE_WRITERS)}"
        )
    return factory()
