"""Local persistence: what we have seen, what changed, and what you did about it."""

from __future__ import annotations

from .changes import Change, ChangeSet, detect_changes
from .database import (
    ACTIVE_STATUSES,
    ACTIVITY_LEAD_CREATED,
    ACTIVITY_LEAD_UPDATED,
    ACTIVITY_NOTE_ADDED,
    ACTIVITY_OFFER_CALCULATED,
    ACTIVITY_PRICE_CHANGED,
    ACTIVITY_RESEARCH_COMPLETED,
    ACTIVITY_SCORE_CHANGED,
    ACTIVITY_STATUS_CHANGED,
    ACTIVITY_TYPES,
    CLOSED_STATUSES,
    DECISION_GO,
    DEFAULT_DB_PATH,
    LEAD_STATUSES,
    SIGNAL_FILTER_FIELDS,
    SORT_KEYS,
    STATUS_ASSIGNED,
    STATUS_CLOSED,
    STATUS_CONTACT,
    STATUS_DEAD,
    STATUS_HOT,
    STATUS_NEW,
    STATUS_OFFER_SENT,
    STATUS_ORDER,
    STATUS_PASSED,
    STATUS_RESEARCHED,
    STATUS_UNDER_CONTRACT,
    STATUS_WATCH,
    LeadSnapshot,
    LeadStore,
    SearchQuery,
    StoredLead,
    dedupe_key,
)

__all__ = [
    "ACTIVE_STATUSES",
    "ACTIVITY_LEAD_CREATED",
    "ACTIVITY_LEAD_UPDATED",
    "ACTIVITY_NOTE_ADDED",
    "ACTIVITY_OFFER_CALCULATED",
    "ACTIVITY_PRICE_CHANGED",
    "ACTIVITY_RESEARCH_COMPLETED",
    "ACTIVITY_SCORE_CHANGED",
    "ACTIVITY_STATUS_CHANGED",
    "ACTIVITY_TYPES",
    "CLOSED_STATUSES",
    "Change",
    "DECISION_GO",
    "ChangeSet",
    "DEFAULT_DB_PATH",
    "LEAD_STATUSES",
    "LeadSnapshot",
    "LeadStore",
    "SIGNAL_FILTER_FIELDS",
    "SORT_KEYS",
    "STATUS_ASSIGNED",
    "STATUS_CLOSED",
    "STATUS_CONTACT",
    "STATUS_DEAD",
    "STATUS_HOT",
    "STATUS_NEW",
    "STATUS_OFFER_SENT",
    "STATUS_ORDER",
    "STATUS_PASSED",
    "STATUS_RESEARCHED",
    "STATUS_UNDER_CONTRACT",
    "STATUS_WATCH",
    "SearchQuery",
    "StoredLead",
    "dedupe_key",
    "detect_changes",
]
